name: Java CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Run Maven tests
        run: mvn verify

      - name: Run Integration.py
        run: python -m unittest discover -v -s . -p integration.py
      
      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('~/.sonar/cache/**') }}
          restore-keys: ${{ runner.os }}-sonar
          
      - name: Build and analyze with SonarQube
        run: mvn clean verify sonar:sonar -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Cache CIFuzz Corpus
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.cifuzz-corpus
          key: ${{ runner.os }}-cifuzz-${{ hashFiles(format('{0}/.cifuzz-corpus/**', github.workspace)) }}
          restore-keys: ${{ runner.os }}-cifuzz

      - name: Run CIFuzz
        env:
          JAZZER_FUZZ: 1
        run: mvn surefire:test -Dtest=BitParserFuzzTest && mvn surefire:test -Dtest=ByteParserFuzzTest && mvn surefire:test -Dtest=HexParserFuzzTest && mvn surefire:test -Dtest=IntParserFuzzTest
      
      - name: Build
        run: mvn install

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: panbyte-jar
          path: target/panbyte.jar